name: Run Newman Tests

on:
  push:
    branches:
      - main  # Runs on any push to the 'main' branch
  pull_request:
    branches:
      - main  # Runs when a pull request is made to 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use v3 (v2 is a bit old)

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Upgrade to v3 for stability
        with:
          node-version: '14'  # You can upgrade to '16' or '18' if your project supports it

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          newman run "postman/GoRest API- CRUD Operations.postman_collection.json" \
            -e "postman/GoRest-QA.postman_environment.json" \
            -d "data/GoRest.csv" \
            -r cli,html --reporter-html-export newman-report.html

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html
