name: Run Newman Tests

on:
  push:
    branches:
      - main  # Runs on any push to the 'main' branch
  pull_request:
    branches:
      - main  # Runs when a pull request is made to 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js version 14 (or adjust as needed)

      - name: Install Newman
        run: npm install -g newman  # Install the Newman tool globally

      - name: Run Postman Tests
        run: |
          newman run "postman/GoRest API- CRUD Operations.postman_collection.json" -e "postman/GoRest-QA.postman_environment.json" -d "data/GoRest.csv" -r cli,html --reporter-html-export newman-report.html
          # Adjusted paths to reflect file locations in 'postman' and 'data' folders

      - name: Upload Newman Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-report
          path: newman-report.html  # Uploads the HTML report generated by Newman
