name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman + HTML Reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Tests
        run: |
          newman run "postman/GoRest API- CRUD Operations.postman_collection.json" \
            -e "postman/GoRest-QA.postman_environment.json" \
            -d "data/GoRest.csv" \
            -r cli,html --reporter-html-export ./newman-report.html

      - name: List files in workspace
        run: ls -R

      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: ./newman-report.html
